---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: true
configure_zsh: true
configure_oh_my_zsh: false


# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: 
  - Maps
  - Facetime
# - Launchpad
  - TV
  - Podcasts
# - 'App Store'
  - Numbers
  - Pages
  - Keynote
  - Music
  - Facetime
dockitems_persist: 
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 18

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - kubectl
  - kubectx
  - helm
  - azure-cli
  - mas
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-history-substring-search
  - zsh-autosuggestions

  - bitwarden-cli
  - k9s
  - golang
  - pulumi
  - kind
  - tree
  - neofetch
  - btop
  - cmatrix
  - neovim

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - slack
  - vagrant
  - vmware-horizon-client
  - citrix-workspace
  - visual-studio-code
  - bitwarden
  - signal
  - iterm2
  - powershell
  - element
  - font-hack-nerd-font
  - font-cascadia-code
  - font-caskaydia-cove-nerd-font
  - postman-agent
  - rectangle
  - obsidian
  - steam
  - insomnia
  - obs
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# gantsign.oh-my-zsh config
# Default theme
#oh_my_zsh_theme: robbyrussell

# Default plugins
#oh_my_zsh_plugins:
#  - git

# Wether to install by default for all specified users.
# May be overridden by `oh_my_zsh: install:` under each user.
oh_my_zsh_install: yes

# User configuration
# Important: oh-my-zsh is installed per user so you need to specify the users to install it for.
#users:
#  - username: me
#    oh_my_zsh:
#      theme: powerlevel10k/powerlevel10k
#      plugins:
#        - git
#        - zsh-syntax-highlighting

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []